version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5c:cb:0c:24:9a:5e:72:29:9f:53:b4:c9:93:60:4c:c8"
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t joseguzman21/circleci-cd:$CIRCLE_SHA1 .
      - run: docker push joseguzman21/circleci-cd:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no root@147.182.173.130 "/bin/bash /root/docker/deploy.sh $CIRCLE_SHA1"